### ISSUE TITLE
json.decoder.JSONDecodeError: Extra data: line 19 column 

### ISSUE THREAD

**Issue by wojciech-kulik** [SolaWing/xcode-build-server#71]
When I run:
```
xcode-build-server config -project XYZ.xcodeproj -scheme "XYZ Dev"
```

I get this error:
```
find root: /Users/wkulik/Library/Developer/Xcode/DerivedData/XYZ-gpmdmkkdwesporflxvnrnqbsyoll
Traceback (most recent call last):
  File "/opt/homebrew/bin/xcode-build-server", line 109, in <module>
    main()
  File "/opt/homebrew/bin/xcode-build-server", line 76, in main
    main(subcommand_argv())
  File "/opt/homebrew/Cellar/xcode-build-server/1.1.0/libexec/config/cmd.py", line 92, in main
    config = ServerConfig.shared()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/xcode-build-server/1.1.0/libexec/config/config.py", line 59, in shared
    return ServerConfig(ServerConfig.default_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/xcode-build-server/1.1.0/libexec/config/config.py", line 65, in __init__
    self.data = json.load(f)
                ^^^^^^^^^^^^
  File "/nix/store/ybnf7k6i9p244bbhsbxizqk65z58cwyr-python3-3.12.6/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/nix/store/ybnf7k6i9p244bbhsbxizqk65z58cwyr-python3-3.12.6/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/ybnf7k6i9p244bbhsbxizqk65z58cwyr-python3-3.12.6/lib/python3.12/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 19 column 2 (char 456)
```

I installed `xcode-build-server` via Homebrew. I'm using Xcode 16 on macOS Sequoia.

Any idea how to fix it?

**Comment by SolaWing** [comment]
Did your buildServer.json is valid? did you modify it?

**Comment by wojciech-kulik** [comment]
Hmm, the scheme was different, so it looks like this command doesn't support updating scheme. When I deleted `buildServer.json` it worked

**Comment by SolaWing** [comment]
it support update, but the error shows your json file is corrupted

**Comment by wojciech-kulik** [comment]
Hmm, not sure why it would happen, the file seemed to be fine, I didn't do any manual changes. Nevertheless, the issue doesn't occur anymore, so I'm closing the ticket.
